### ISSUE TITLE
Time increasing all the time

### ISSUE THREAD

**Issue by zmwv823** [ty0x2333/ComfyUI-Dev-Utils#1]
The time won't stop in each node even queue stoped.
**win10+py311+torch2.2.2+cu121**
![image](https://github.com/ty0x2333/ComfyUI-Dev-Utils/assets/13308350/f3fad3ea-d32a-4ca0-8592-b81ad6c7b7d4)

**Comment by ty0x2333** [comment]
@zmwv823 Please upgrade ComfyUI to the latest version.

**Comment by zmwv823** [comment]
> @zmwv823 Please upgrade ComfyUI to the latest version.

My fault.
My pc is down, git never works with proxy even with "git config" args.
Comfyui was broken, it's version shows 1900.

**Comment by zmwv823** [comment]
> @zmwv823 Please upgrade ComfyUI to the latest version.

**It's not a issue or request.**
After reinstall comfyui，still get this error.
Finally i found it's incompitable with another node.Maybe some method duplicated.
https://gitee.com/yanlang0123/ComfyUI_Lam
