### ISSUE TITLE
`getSlotMenuOptions.apply` incorrectly applying arguments when right clicking on slots.

### ISSUE THREAD

**Issue by Trung0246** [ty0x2333/ComfyUI-Dev-Utils#18]
https://github.com/ty0x2333/ComfyUI-Dev-Utils/blob/3f66a0b82fa7ae889a0a86ce92bba607d27e6f55/web/reroute.js#L13

I think it should be something like this:

```js
menuInfo = getSlotMenuOptions.apply(this, [slot]);
```

**Comment by ty0x2333** [comment]
The line of code

```
menuInfo = getSlotMenuOptions.apply(this, slot); 
```

is fine.

Below is the location of the relevant code in litegraph.js:

[jagenjo/litegraph.js - litegraph.d.ts](https://github.com/jagenjo/litegraph.js/blob/0555a2f2a3df5d4657593c6d45eb192359888195/src/litegraph.d.ts#L1036)

```
getSlotMenuOptions?(slot: INodeSlot): ContextMenuItem[];
```

[Interface INodeSlot](https://github.com/jagenjo/litegraph.js/blob/0555a2f2a3df5d4657593c6d45eb192359888195/src/litegraph.d.ts#L1038)

```
export interface INodeSlot {
    name: string;
    type: string | -1;
    label?: string;
    dir?:
        | typeof LiteGraph.UP
        | typeof LiteGraph.RIGHT
        | typeof LiteGraph.DOWN
        | typeof LiteGraph.LEFT;
    color_on?: string;
    color_off?: string;
    shape?: SlotShape;
    locked?: boolean;
    nameLocked?: boolean;
}
```

@Trung0246

**Comment by Trung0246** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

I think you probably misunderstood. On recent update, right clicking on input/output slot will cause error when running that line of code, which will no longer shows the actual right click menu.

**Comment by Trung0246** [comment]
@ty0x2333 the web console should shows the error when right clicking on the slot, removing that line or changing the fix I suggested make everything works again.

![image](https://github.com/user-attachments/assets/b6495214-3d08-4f24-9623-1f773a64fe5a)

**Comment by ty0x2333** [comment]
Thank you. This is indeed a bug. I will release a minor version to fix it. @Trung0246
