### ISSUE TITLE
Right-click context menu doesn't appear

### ISSUE THREAD

**Issue by De-Zoomer** [ty0x2333/ComfyUI-Dev-Utils#19]
Right-click context menu doesn't show up when this extension is installed. 

The context menu that doesn't show is the one to rename a node input for example:

<img width="398" alt="Screenshot 2024-09-17 at 22 02 43" src="https://github.com/user-attachments/assets/7f9e51c6-d201-4e7d-8c01-1f18ed357d9e">

**Comment by ty0x2333** [comment]
You need to right-click on the Dot’s position.

<img width="398" alt="368323168-7f9e51c6-d201-4e7d-8c01-1f18ed357d9e" src="https://github.com/user-attachments/assets/cec1ce36-b2e9-4ac4-b200-473dfa4d05ce">

@De-Zoomer
