### ISSUE TITLE
Add "Reroute" option to node slot menu.

### ISSUE THREAD

**Issue by 807502278** [ty0x2333/ComfyUI-Dev-Utils#2]
Add "Reroute" option to node slot menu.

How was this menu ordered???

**Comment by ty0x2333** [comment]
After installation, all Node Slots that meet the following conditions will automatically add the Reroute menu item:

1. Slot is Output Slot (on the right side of Node)
2. Slot is currently connected

Point the mouse to the Slot and right-click to see the Reroute menu item.

<img width="698" alt="2024-04-26 15 06 37" src="https://github.com/ty0x2333/ComfyUI-Dev-Utils/assets/7489176/4a6788c2-8b98-4c16-bb16-d617c9b14114">

@807502278

**Comment by ty0x2333** [comment]
![](https://github.com/ty0x2333/ComfyUI-Dev-Utils/wiki/images/after-reroute.gif)

This gif shows the usage. @807502278
