### ISSUE TITLE
The time keeps increasing...And the "Execution Time" node doesn't work.

### ISSUE THREAD

**Issue by wudideasdf** [ty0x2333/ComfyUI-Dev-Utils#4]
Seems to be a conflict with another plugin?
Already updated to the latest version.

**Comment by ty0x2333** [comment]
Can you provide more info? Provides a list of plugins. Or help me find the conflicting plugin.
@wudideasdf

**Comment by wudideasdf** [comment]
> Can you provide more info? Provides a list of plugins. Or help me find the conflicting plugin.您能提供更多信息吗？提供插件列表。或者帮我找到有冲突的插件。 @wudideasdf

I'll try to find it.

**Comment by wudideasdf** [comment]
> Can you provide more info? Provides a list of plugins. Or help me find the conflicting plugin.您能提供更多信息吗？提供插件列表。或者帮我找到有冲突的插件。 @wudideasdf

I troubleshooted over 120 plugins and finally locked it down:
https://github.com/yanlang0123/ComfyUI_Lam
(https://gitee.com/yanlang0123/ComfyUI_Lam)

**Comment by ty0x2333** [comment]
Thanks, I noticed a conflict with `ComfyUI-Workflow-Component` and fixed it.

I'm not sure it's the same issue, but I installed yanlang0123/ComfyUI_Lam and successfully ran `ExecuteTime`.

Please try updating ComfyUI-Dev-Utils.

@wudideasdf
