### ISSUE TITLE
1 error

### ISSUE THREAD

**Issue by T8star1984** [ty0x2333/ComfyUI-Dev-Utils#5]
the node conflict with 'ComfyUI_Lam' node,the time will be show all the time and it won't stop

**Comment by ty0x2333** [comment]
Same: #4

**Comment by ty0x2333** [comment]
Please update ComfyUI-Dev-Utils. and try again. @T8star1984

**Comment by ty0x2333** [comment]
This BUG has been resolved in the latest version. I'll close this issue. If you have other questions, you can reopen it.
